---

- include_tasks: context.yml

- name: set network configuration with netplan
  include_tasks: netplan.yml
  when: ansible_distribution == 'Ubuntu'

- name: configure network on FreeBSD
  include_tasks: freebsd.yml
  when: ansible_system == 'FreeBSD'
