---
network:
  version: 2
  renderer: networkd
  ethernets:
    {{ ansible_default_ipv4.interface }}:
      addresses:
        - {{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ipsubnet }}
      gateway4: {{ ansible_default_ipv4.gateway }}
      nameservers:
          search: {{ domain_search }}
          addresses: {{ domain_nameservers }}
#          options: {{ ansible_dns.options }}
      dhcp4: no
      dhcp6: no
